version: '3.4'

services:
  demoproject:
    image: demoproject
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5160:5160
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
